language: python
sudo: required
python:
  - "2.7"
install:
  - sudo pip install -r requirements
  - sudo pip install coveralls
script:
  - sudo python experiment626.py --help
after_success:
  - sudo coverage experiment626.py -h
  - coveralls


