sudo: required

language: python
cache: pip

python:
  - 2.7

install:
  - pip install -r requirements
  - pip install coveralls docopt coverage

script:
  - sudo coverage run experiment626.py -h

after_success:
  - coveralls

